name: CD Homologação

on:
 workflow_run:
    workflows: ["CI Azure Function"]
    branches: [develop]
    types:
      - completed
env:        
  OUTPUT_PATH:  ${{ github.workspace }}/.output    
 
jobs:
  Homologation:
    name: Deploy to homologation
    environment: Homologation
    runs-on: ubuntu-latest
    
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:    
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: CI.yml
        workflow_conclusion: success
        name: functions-artifact
  
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'     
   
    - name: Deploy Azure Functions
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: gabriel-teste
        package: ${{ env.OUTPUT_PATH }}
        publish-profile: ${{ env.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

