name: CD Homologação

on:
 workflow_run:
    workflows: ["CI Azure Function"]
    branches: [develop]
    types:
      - completed
 
jobs:
  Homologation:
    name: Deploy to homologation
    environment: Homologation
    runs-on: windows-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: functions-artifact
