name: CI Azure Function

on:
 push:
    branches: [ develop, main, feature/*, hotfix/* ]
 pull_request:
    branches: [ develop, main ]
 workflow_dispatch: 
  
env:
  AZURE_FUNCTIONAPP_NAME: publisherNow
  DOTNET_VERSION: '3.1'             
  OUTPUT_PATH: ${{ github.workspace }}/.output
  
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
        
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup DotNet ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore and Build project
      shell: pwsh
      run: dotnet restore && dotnet publish --configuration Release --output ${{ env.OUTPUT_PATH }}
      
    - name: Unit Tests
      run: dotnet test --no-restore --verbosity normal

