name: Deploy Azure Function

on:
  push:
      branches: main
  workflow_dispatch:
  
env:
  AZURE_FUNCTIONAPP_NAME: publisherNow
  AZURE_FUNCTIONAPP_PACKAGE_PATH:  /AzureFunctionGitHubAction 
  DOTNET_VERSION: '3.1'             
  OUTPUT_PATH: ${{ github.workspace }}/.output
  
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
    
    - name: Configuring Azure secrets
      uses: azure/appservice-settings@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        app-settings-json: '${{ secrets.APP_SETTINGS }}' 
        connection-strings-json: '${{ secrets.CONNECTION_STRINGS }}'
        general-settings-json: '{"alwaysOn": "false", "webSocketsEnabled": "true"}' #'General configuration settings as Key Value pairs'
      id: settings
    - run: |
        az logout
        
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup DotNet ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore and Build project
      shell: pwsh
      run: dotnet restore && dotnet publish --configuration Release --output ${{ env.OUTPUT_PATH }}
      
    - name: Unit Tests
      run: dotnet test --no-restore --verbosity normal
      
    - name: Run Azure Functions
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.OUTPUT_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

