name: Deploy DotNet project to Azure Function App

on:
  push:
      branches: main

env:
  AZURE_FUNCTIONAPP_NAME: function_action
  AZURE_FUNCTIONAPP_PACKAGE_PATH:  /AzureFunctionGitHubAction 
  DOTNET_VERSION: '3.1'             
  OUTPUT_PATH: ${{ github.workspace }}/.output
  
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Build project'
      shell: pwsh
      run: dotnet publish --configuration Release --output ${{ env.OUTPUT_PATH }}
      
      name: Test
      run: dotnet test --no-restore --verbosity normal
    - 
      name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.OUTPUT_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

