name: CI/CD for Azure Function

on:
 push:
    branches: [ develop, main, feature/*, hotfix/* ]
 pull_request:
    branches: [ develop, main ]
 workflow_dispatch: 
  
env:
  AZURE_FUNCTIONAPP_NAME: publisherNow
  DOTNET_VERSION: '3.1'             
  OUTPUT_PATH: ${{ github.workspace }}/artifacts
  ARTIFACT_NAME: functions-artifact
  
jobs:
 Build:
    runs-on: ubuntu-latest
    steps:
        
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup DotNet ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore and Build project
      shell: pwsh
      run: dotnet restore && dotnet publish --configuration Release --output ${{ env.OUTPUT_PATH }}
      
    - name: Unit Tests
      run: dotnet test --no-restore --verbosity normal
    
    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
       name: ${{ env.ARTIFACT_NAME }}
       path: ${{ env.OUTPUT_PATH }}
       
 Homologation:
     needs: Build
     if: github.ref == 'refs/heads/develop'
     name: Deploy to homologation
     environment: Homologation
     runs-on: ubuntu-latest
     
     steps:
     - name: Download artifacts
       uses: actions/download-artifact@v2
       with:
        name: ${{ env.ARTIFACT_NAME }}
        
     - name: Azure Login
       uses: azure/login@v1
       with:
         creds: '${{ secrets.AZURE_CREDENTIALS }}'     
   
     - name: Deploy Azure Functions
       uses: Azure/functions-action@v1
       id: fa
       with:
         app-name: gabriel-teste
         publish-profile: ${{ env.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}   

